
package com.vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "DeviceUnsupportedForVmVersionFault", targetNamespace = "urn:vim25")
public class DeviceUnsupportedForVmVersionFaultMsg
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private DeviceUnsupportedForVmVersion faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public DeviceUnsupportedForVmVersionFaultMsg(String message, DeviceUnsupportedForVmVersion faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public DeviceUnsupportedForVmVersionFaultMsg(String message, DeviceUnsupportedForVmVersion faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.vmware.vim25.DeviceUnsupportedForVmVersion
     */
    public DeviceUnsupportedForVmVersion getFaultInfo() {
        return faultInfo;
    }

}
