
package com.vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "KeyNotFoundFault", targetNamespace = "urn:vim25")
public class KeyNotFoundFaultMsg
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private KeyNotFound faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public KeyNotFoundFaultMsg(String message, KeyNotFound faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public KeyNotFoundFaultMsg(String message, KeyNotFound faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.vmware.vim25.KeyNotFound
     */
    public KeyNotFound getFaultInfo() {
        return faultInfo;
    }

}
