
package com.vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "MissingControllerFault", targetNamespace = "urn:vim25")
public class MissingControllerFaultMsg
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private MissingController faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public MissingControllerFaultMsg(String message, MissingController faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public MissingControllerFaultMsg(String message, MissingController faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.vmware.vim25.MissingController
     */
    public MissingController getFaultInfo() {
        return faultInfo;
    }

}
