
package com.vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "SSLVerifyFaultFault", targetNamespace = "urn:vim25")
public class SSLVerifyFaultFaultMsg
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private SSLVerifyFault faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public SSLVerifyFaultFaultMsg(String message, SSLVerifyFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public SSLVerifyFaultFaultMsg(String message, SSLVerifyFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.vmware.vim25.SSLVerifyFault
     */
    public SSLVerifyFault getFaultInfo() {
        return faultInfo;
    }

}
